name: Run get_short_range_prediction

on:
    workflow_dispatch: # 手動実行を許可
    schedule:
      - cron: '0 21 * * *' # 日本時間 6:00 (UTC 21:00)
      - cron: '0 9 * * *'  # 日本時間 18:00 (UTC 9:00)

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Japanese fonts
        run: sudo apt-get install -y fonts-noto-cjk

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python get_short_range_prediction.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: short-range-output-zip
          path: output.zip